# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3f5c8550a2eb09efedf94449db838ee6defe9c0eeaf018ace74752bed23b33b7aae30f73ca46ffb43238e6bf375288c5a25f32439962c3a5b5bb93230e99d4b

test:
  secret_key_base: 6ec4ee81d2594be08361e17a0ad0be8c8cf1889728c76b5e58d8a7478334ac6e53c7e0e9e6acee115780785bfa99654de8ec9b3b8ffaa9c21d8c2e6150b145b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
